Retweet
jwspgcr/FA-Django pull request #4
Opened 2021-02-11 16:55 UTC by jwspgcr

リツイート機能を追加しました。よろしくお願いいたします。

2021-03-05 12:00 UTC, kpppn reviewed
全体的によくできていると思います
ただ、現在の実装ですとリツイートが複数人しても何度もタイムラインに流れてこないことと誰がリツイートしたかわからないです。
余裕があれば対応してみてください

2021-03-07 14:20 UTC, jwspgcr reviewed
よろしくお願いいたします。

2021-03-07 14:20 UTC, jwspgcr commented on SNS/views.py
>              p.keyDate = p.repost_set.latest("pub_date").pub_date
ご指摘頂いた点を取り込んだ認識ですのでご確認いただければ幸いです。
ただ、2点不安な点があります。
①上に引用した箇所で、ループごとにDBへのアクセスが発生しているような気がします（いわゆるN+1問題でしょうか？）。改善策をアドバイスを頂ければ幸いです（prefetch_relatedというのを使おうとしたのですがいまいち使い方が理解できませんでした）。
②組み込みのクラスベースビューでは、テンプレートに渡すデータはget_querysetで取得したクエリセットとするのが定石なのかなと思っています（違っていたらご指摘ください）。しかし今回は、postsRepostedは最新のリツイート日時、postsNotRepostedはツイート日時を使って並べ替える必要があり、これらの日時データをクエリセットに持たせる方法が分かりませんでした。そのため、クラスベースビューを諦めて関数ビューとし、モデルのインスタンスをリストにしてテンプレートに渡しています。より良い方法があればご教示ください。
お手数ですがよろしくお願いいたします。

2021-03-27 04:06 UTC, kpppn commented on SNS/views.py
>              p.keyDate = p.repost_set.latest("pub_date").pub_date
①N+1問題ですね。`select_related` というのがあるんですが、そちらを使うほうが今回は最適化かもしれないです。
現在の実装ですと、`Post.objects.filter(...)` `となっていますが、このやり方ですとPostのカラムしかselectしないSQLが発行されます。`select_related` を使用して関連するテーブルのカラム情報も取得することで何度もクエリを発行するのを防げると思います。
django reference: https://docs.djangoproject.com/en/3.1/ref/models/querysets/#select-related

発行されるクエリ (生成されるクエリは長いので見やすいとこにコピペしてください
```python
print(Post.objects.filter(Q(repost__repostedBy__in=myFollowers)).query)

SELECT "SNS_post"."id", "SNS_post"."author_id", "SNS_post"."replyTo_id", "SNS_post"."text", "SNS_post"."pub_date" FROM "SNS_post" INNER JOIN "SNS_repost" ON ("SNS_post"."id" = "SNS_repost"."post_id") WHERE "SNS_repost"."repostedBy_id" IN (SELECT U0."user_id" FROM "SNS_customuser" U0 INNER JOIN "SNS_customuser_followers" U1 ON (U0."user_id" = U1."to_customuser_id") WHERE U1."from_customuser_id" = 2)
```

select_relatedを使用すると関連するテーブルのカラムもselect対象になります。

発行されるクエリ (生成されるクエリは長いので見やすいとこにコピペしてください)
```python
print(Repost.objects.select_related('post').filter(Q(repostedBy__in=myFollowers)).query)

SELECT "SNS_repost"."id", "SNS_repost"."repostedBy_id", "SNS_repost"."post_id", "SNS_repost"."pub_date", "SNS_post"."id", "SNS_post"."author_id", "SNS_post"."replyTo_id", "SNS_post"."text", "SNS_post"."pub_date" FROM "SNS_repost" INNER JOIN "SNS_post" ON ("SNS_repost"."post_id" = "SNS_post"."id") WHERE "SNS_repost"."repostedBy_id" IN (SELECT U0."user_id" FROM "SNS_customuser" U0 INNER JOIN "SNS_customuser_followers" U1 ON (U0."user_id" = U1."to_customuser_id") WHERE U1."from_customuser_id" = 1)
```

②おっしゃる通りクラスベースビューは決まった型のときに価値を発揮するもので、型から外れる場合に無理に使用する必要性はまったくありません。関数ベースビューを選ぶことは問題ないですし、クラスベースビューの中でも `TemplateView` は `ListView` より抽象的なクラスですので、今回の場合はそちらの利用でもよいかと思います。

2021-03-27 04:07 UTC, kpppn commented on SNS/views.py
> +    else:
上のifに入った場合はreturnしているのでここでのelseはいらなそうですね

2021-03-28 15:05 UTC, jwspgcr commented on SNS/views.py
>              p.keyDate = p.repost_set.latest("pub_date").pub_date
レビューいただきありがとうございます。
①select_relatedを用いてviewを書き直し、発行されたSQLクエリをDjango Debug Toolbarで確認してみました。
![django_debug_toolbar](https://user-images.githubusercontent.com/76438071/112756881-2a6dd800-8f8b-11eb-82fd-8fa40ab265d0.jpg)
添付した画面の通り、今まで複数回発行されていたクエリが一回に集約されました。
またテンプレートのレンダリング時に起きていたN＋１問題も併せて対応しておきました。
②承知しました。今回は関数ビューを使うことにします。
③タイムライン上でのポストの並び順についてテストコード(SNS/tests.py)を書いてみましたので、違和感のある書き方になっていないかご確認いただければ幸いです。

2021-03-28 15:19 UTC, jwspgcr commented on SNS/views.py
> +    else:
elseを削除しました。

2021-04-05 09:18 UTC, kpppn requested changes
確認おねがいします

2021-04-05 09:18 UTC, kpppn commented on SNS/views.py
> +        p.keyDate = p.pub_date
もしカラム名に別名を与えたい場合はクエリ取得の際にannotationとF式を活用するといいと思います
`.annotate(keyDate=F('pub_date'))`

ref: https://docs.djangoproject.com/ja/3.0/ref/models/expressions/#using-f-with-annotations

2021-04-05 09:18 UTC, kpppn commented on SNS/tests.py
> +        cuserA = create_customuser_from_user(userA)
テストに依存しているものはsetUpメソッドを使用するといいと思います

2021-04-05 09:18 UTC, kpppn commented on SNS/tests.py
> +        self.assertQuerysetEqual(response.context["posts"], ["<Post: userA>"])
querysetの他にもステータスコードのassertもあるとなおいいと思います

2021-04-06 13:11 UTC, jwspgcr commented on SNS/views.py
> +        p.keyDate = p.pub_date
annotateに置き換えました

2021-04-06 13:12 UTC, jwspgcr commented on SNS/tests.py
> +        cuserA = create_customuser_from_user(userA)
setUPを使用しました

2021-04-06 13:12 UTC, jwspgcr commented on SNS/tests.py
> +        self.assertQuerysetEqual(response.context["posts"], ["<Post: userA>"])
ステータスコードが200であることを確認するケースを追加しました

2021-04-09 02:33 UTC, kpppn approved these changes

2021-04-09 03:05 UTC, merged